# type Color {
#   r: Int!
#   g: Int!
#   b: Int!
# }

type Project {
  id: ID!
  userId: ID!
  title: String!
  # color: Color
  color: String
}

extend type Query {
  allProjects: [Project!]
}

extend type Mutation {
  # createProject(title: String!, r: Int, g: Int, b: Int): Project
  createProject(title: String!, color: String): Project
  updateProject(id: ID!, title: String, color: String): Project
}
