type TimeEntry {
  id: ID!
  projectId: ID!
  userId: ID!
  startTime: Float!
  endTime: Float
}

extend type Query {
  currentTimeEntry: TimeEntry
  # currentTimeEntry: TimeEntry
}

extend type Mutation {
  toggle(projectId: ID!): TimeEntry!
}
