enum Role {
  ADMIN
  CLIENT
}

type User {
  id: ID!
  name: String!
  email: String!
  password: String!
  picture: String
  # role: Role!
  projects: [Project!]
}

type Query {
  allUsers: [User!]!
}

type Mutation {
  createUser(name: String!, email: String!, password: String!): User
  refreshToken(oldToken: String!): SigninPayload!
  signIn(email: String!, password: String!): SigninPayload!
  signInGoogle(token: String!): SigninPayload!
}

type SigninPayload {
  token: String
  user: User
}
