enum Role {
  ADMIN
  CLIENT
}

type User {
  id: ID!
  name: String!
  email: String!
  picture: String
  role: Role!
}

type Query {
  allUsers: [User!]!
}

type Mutation {
  refreshToken(oldToken: String!): SigninPayload!
  signInGoogle(token: String!): SigninPayload!
}

type SigninPayload {
  token: String
  user: User
}
